# This is a basic workflow to help you get started with Actions

name: dbt_run_setting_sched

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  schedule:
    - cron: '0 6 * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Set current date as env variable
        run: echo "NOW=$(date +'%Y-%m-%dT%H:%M:%S')" >> $GITHUB_ENV
      - name: Echo current date
        run: echo $NOW # Gives "2022-12-11T01:42:20"
      - name: Echo schedule info
        run: echo github.event.schedule
      - name: test run on if condition
        if: github.event.schedule == '0 6 * * *'
        run: echo Hi this is test run with if condition bk
      - name: dbt-action
        uses: mwhitaker/dbt-action@master
        with:
          dbt_command: "dbt run -m test_tag1"
          dbt_project_folder: "jaffle_shop"
        env:
          account: wuihetv-mt05564
          database: SEEKMART_OMS
          password: Mytestacc1$
          role: ACCOUNTADMIN
          schema: L3_CONSUMPTION
          threads: 1
          type: snowflake
          user: bikkoi503
          warehouse: COMPUTE_WH
