# This is a basic workflow to help you get started with Actions

name: scheduletest3

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  schedule:
    - cron: '43 5,6,7 * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Set current date as env variable
        run: echo "NOW=$(date +'%Y-%m-%dT%H:%M:%S')" >> $GITHUB_ENV
      - name: Echo current date
        run: echo $NOW # Gives "2022-12-11T01:42:20"
      - name: test run on if condition5
        if: github.event.schedule == '43 5 * * *'
        run: echo Hi this is test run for 43 5
      - name: regular run of schedule
        run: echo Hi this is regular run of schedule
      - name: test run on if condition6
        if: github.event.schedule == '43 6 * * *'
        run: echo Hi this is test run for 43 6
      - name: test run on if condition7
        if: github.event.schedule == '43 7 * * *'
        run: echo Hi this is test run for 43 7
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "$GITHUB_CONTEXT"

        
        
